# ─────────────────────────────
# Cấu hình Plugin Store
# ─────────────────────────────

[DatabaseConnection]
# Tên máy chủ hoặc địa chỉ IP của máy chủ MySQL
Host = ""

# Cổng máy chủ MySQL (thường là 3306)
Port = 3306

# Tên người dùng để xác thực cơ sở dữ liệu
User = ""

# Mật khẩu để xác thực cơ sở dữ liệu
Pass = ""

# Tên của cơ sở dữ liệu được sử dụng
Name = ""

# Bảng được sử dụng để lưu trữ dữ liệu người chơi (credits, v.v.)
StorePlayersName = "store_players"

# Bảng được sử dụng để lưu trữ dữ liệu vật phẩm
StoreItemsName = "store_items"

# Bảng được sử dụng để lưu trữ các vật phẩm người chơi đã trang bị
StoreEquipments = "store_equipments"

# ─────────────────────────────

[Commands]
# Các lệnh thay thế có thể được sử dụng bởi người chơi. Bạn có thể thêm nhiều lệnh khác.
Credits = [ "xyz834abc", "def012mno" ]
Store = [ "svip" ]
Inventory = [ "inv" ]
GiveCredits = [ "nop234qrs" ]
Gift = [ "tuv567wxy" ]
ResetPlayer = [ "zab890cde" ]
ResetDatabase = [ "fgh123ijk" ]
RefreshPlayersCredits = [ "lmn456opq" ]
HideTrails = [ "rst789uvw" ]
PlayerSkinsOff = [ "xyz012abc", "def345ghi" ]
PlayerSkinsOn = [ "jkl678mno", "pqr901stu" ]

# ─────────────────────────────

[DefaultModels]
# Mô hình người chơi mặc định cho mỗi đội. Để trống nếu không sử dụng.
Terrorist = [ "" ]
CounterTerrorist = [ "" ]

# Nếu true, vô hiệu hóa chân của các mô hình mặc định.
DefaultModelDisableLeg = false

# ─────────────────────────────

# Quy tắc nhận credits cho các nhóm quyền cụ thể.
# Các quyền ưu tiên cao nên được đặt trên các quyền thấp hơn.
# KHÔNG bao gồm 'Start', 'IgnoreWarmup', hoặc 'IntervalActiveInActive' trong bất kỳ nhóm nào ngoài "default".

[Credits."@css/root"]
AmountActive = 0       # Credits nhận được khi hoạt động
AmountInActive = 0     # Credits nhận được khi không hoạt động
AmountKill = 3         # Credits nhận được mỗi lần giết

[Credits."@zhw/svipflg"]
AmountActive = 0       # Credits nhận được khi hoạt động
AmountInActive = 0     # Credits nhận được khi không hoạt động
AmountKill = 0         # Credits nhận được mỗi lần giết

[Credits."default"]
# Các trường này CHỈ được phép trong nhóm "default"
Start = 500                     # Số dư credits ban đầu cho người chơi mới
IgnoreWarmup = true             # Nếu true, vô hiệu hóa nhận credits trong thời gian khởi động
IntervalActiveInActive = 1999   # Khoảng thời gian (giây) người chơi nhận credits
AmountActive = 0                # Credits nhận được khi hoạt động
AmountInActive = 0              # Credits nhận được khi không hoạt động
AmountKill = 0                  # Credits nhận được mỗi lần giết

# ─────────────────────────────

[Menu]
# Bật menu xác nhận trước khi hoàn tất mua hàng
EnableConfirmMenu = true

# Loại giao diện menu sử dụng
# Các giá trị hỗ trợ: ConsoleMenu, ChatMenu, CenterHtmlMenu, WasdMenu, ScreenMenu
MenuType = "WasdMenu"

# Người dùng có cờ này có thể trang bị vật phẩm mà không cần trả tiền
# Để trống để vô hiệu hóa đặc quyền VIP
VipFlag = "@zhw/testerflg"

# Âm thanh phát khi xác nhận
MenuPressSoundYes = "sounds/ui/panorama/lobby_gotinvited.vsnd_c"

# Âm thanh phát khi từ chối
MenuPressSoundNo = "sounds/ui/panorama/lobby_error_01.vsnd_c"

# Nếu false, menu sẽ mở cho đến khi bạn đóng nó
CloseMenuAfterSelect = false

# ─────────────────────────────

[Settings]
# Tiền tố tin nhắn cho plugin store (hỗ trợ mã màu như {red}, {green})
Tag = "{gold}7Mau {silver}» "

# Máu tối đa cho phép thông qua vật phẩm store (0 = vô hạn)
MaxHealth = 0

# Giáp tối đa cho phép thông qua vật phẩm store (0 = vô hạn)
MaxArmor = 0

# Tỷ lệ credits nhận được khi bán vật phẩm (ví dụ: 0.6 = 60% giá trị)
SellRatio = 0

# Độ trễ tính bằng giây trước khi áp dụng skin người chơi sau khi chọn
ApplyPlayerskinDelay = 0.1

# Nếu true, bán sẽ trả credits dựa trên giá mà người chơi đã trả
# Nếu false, bán sẽ trả credits dựa trên giá hiện tại trong store
SellUsePurchaseCredit = false

# Bật điều chỉnh tương thích cho CS2 fixes
EnableCs2Fixes = false

# ─────────────────────────────

[Permissions]
# Cờ yêu cầu để chuyển đổi tính năng mô hình người chơi (model0/model1)
Model0Model1Flag = "@zhw/testerflg"

# Cờ yêu cầu để truy cập lệnh /givecredits
GiveCredits = "@zhw/testerflg"
